/**
 * Enterprise Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EnterpriseIntegrationApi);
  }
}(this, function(expect, EnterpriseIntegrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EnterpriseIntegrationApi.DocumentDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DocumentDetails', function() {
    it('should create an instance of DocumentDetails', function() {
      // uncomment below and update the code to test DocumentDetails
      //var instane = new EnterpriseIntegrationApi.DocumentDetails();
      //expect(instance).to.be.a(EnterpriseIntegrationApi.DocumentDetails);
    });

    it('should have the property fileName (base name: "fileName")', function() {
      // uncomment below and update the code to test the property fileName
      //var instane = new EnterpriseIntegrationApi.DocumentDetails();
      //expect(instance).to.be();
    });

    it('should have the property streamLocation (base name: "streamLocation")', function() {
      // uncomment below and update the code to test the property streamLocation
      //var instane = new EnterpriseIntegrationApi.DocumentDetails();
      //expect(instance).to.be();
    });

    it('should have the property fileSize (base name: "fileSize")', function() {
      // uncomment below and update the code to test the property fileSize
      //var instane = new EnterpriseIntegrationApi.DocumentDetails();
      //expect(instance).to.be();
    });

    it('should have the property contentType (base name: "contentType")', function() {
      // uncomment below and update the code to test the property contentType
      //var instane = new EnterpriseIntegrationApi.DocumentDetails();
      //expect(instance).to.be();
    });

  });

}));
