/**
 * Enterprise Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EnterpriseIntegrationApi);
  }
}(this, function(expect, EnterpriseIntegrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EnterpriseIntegrationApi.IngestionResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IngestionResponse', function() {
    it('should create an instance of IngestionResponse', function() {
      // uncomment below and update the code to test IngestionResponse
      //var instane = new EnterpriseIntegrationApi.IngestionResponse();
      //expect(instance).to.be.a(EnterpriseIntegrationApi.IngestionResponse);
    });

    it('should have the property requestTime (base name: "requestTime")', function() {
      // uncomment below and update the code to test the property requestTime
      //var instane = new EnterpriseIntegrationApi.IngestionResponse();
      //expect(instance).to.be();
    });

    it('should have the property deliveryTime (base name: "deliveryTime")', function() {
      // uncomment below and update the code to test the property deliveryTime
      //var instane = new EnterpriseIntegrationApi.IngestionResponse();
      //expect(instance).to.be();
    });

    it('should have the property documentId (base name: "documentId")', function() {
      // uncomment below and update the code to test the property documentId
      //var instane = new EnterpriseIntegrationApi.IngestionResponse();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instane = new EnterpriseIntegrationApi.IngestionResponse();
      //expect(instance).to.be();
    });

    it('should have the property deliveryStatus (base name: "deliveryStatus")', function() {
      // uncomment below and update the code to test the property deliveryStatus
      //var instane = new EnterpriseIntegrationApi.IngestionResponse();
      //expect(instance).to.be();
    });

    it('should have the property statusMessage (base name: "statusMessage")', function() {
      // uncomment below and update the code to test the property statusMessage
      //var instane = new EnterpriseIntegrationApi.IngestionResponse();
      //expect(instance).to.be();
    });

  });

}));
