/*
 * Enterprise Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sphereon.sdk.eip.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sphereon.sdk.eip.model.DocumentDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A document payload containing file info and meta data.
 */
@ApiModel(description = "A document payload containing file info and meta data.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-05T11:35:54.052+02:00")
public class DocumentPayload {
  @SerializedName("documentDetails")
  private DocumentDetails documentDetails = null;

  /**
   * The markup type of the meta data payload
   */
  @JsonAdapter(MetaDataPayloadTypeEnum.Adapter.class)
  public enum MetaDataPayloadTypeEnum {
    JSON("JSON"),
    
    XML("XML");

    private String value;

    MetaDataPayloadTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MetaDataPayloadTypeEnum fromValue(String text) {
      for (MetaDataPayloadTypeEnum b : MetaDataPayloadTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<MetaDataPayloadTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MetaDataPayloadTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MetaDataPayloadTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return MetaDataPayloadTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("metaDataPayloadType")
  private MetaDataPayloadTypeEnum metaDataPayloadType = null;

  @SerializedName("metaDataPayload")
  private String metaDataPayload = null;

  public DocumentPayload documentDetails(DocumentDetails documentDetails) {
    this.documentDetails = documentDetails;
    return this;
  }

   /**
   * A structure containing details about the document name, size, data or data location etc.
   * @return documentDetails
  **/
  @ApiModelProperty(value = "A structure containing details about the document name, size, data or data location etc.")
  public DocumentDetails getDocumentDetails() {
    return documentDetails;
  }

  public void setDocumentDetails(DocumentDetails documentDetails) {
    this.documentDetails = documentDetails;
  }

  public DocumentPayload metaDataPayloadType(MetaDataPayloadTypeEnum metaDataPayloadType) {
    this.metaDataPayloadType = metaDataPayloadType;
    return this;
  }

   /**
   * The markup type of the meta data payload
   * @return metaDataPayloadType
  **/
  @ApiModelProperty(value = "The markup type of the meta data payload")
  public MetaDataPayloadTypeEnum getMetaDataPayloadType() {
    return metaDataPayloadType;
  }

  public void setMetaDataPayloadType(MetaDataPayloadTypeEnum metaDataPayloadType) {
    this.metaDataPayloadType = metaDataPayloadType;
  }

  public DocumentPayload metaDataPayload(String metaDataPayload) {
    this.metaDataPayload = metaDataPayload;
    return this;
  }

   /**
   * The meta data payload
   * @return metaDataPayload
  **/
  @ApiModelProperty(value = "The meta data payload")
  public String getMetaDataPayload() {
    return metaDataPayload;
  }

  public void setMetaDataPayload(String metaDataPayload) {
    this.metaDataPayload = metaDataPayload;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentPayload documentPayload = (DocumentPayload) o;
    return Objects.equals(this.documentDetails, documentPayload.documentDetails) &&
        Objects.equals(this.metaDataPayloadType, documentPayload.metaDataPayloadType) &&
        Objects.equals(this.metaDataPayload, documentPayload.metaDataPayload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentDetails, metaDataPayloadType, metaDataPayload);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentPayload {\n");
    
    sb.append("    documentDetails: ").append(toIndentedString(documentDetails)).append("\n");
    sb.append("    metaDataPayloadType: ").append(toIndentedString(metaDataPayloadType)).append("\n");
    sb.append("    metaDataPayload: ").append(toIndentedString(metaDataPayload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

