/*
 * Enterprise Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sphereon.sdk.eip.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * The response from the ingestion controller.
 */
@ApiModel(description = "The response from the ingestion controller.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-05T11:38:50.794+02:00")
public class IngestionResponse {
  @SerializedName("requestTime")
  private OffsetDateTime requestTime = null;

  @SerializedName("deliveryTime")
  private OffsetDateTime deliveryTime = null;

  @SerializedName("documentId")
  private String documentId = null;

  /**
   * The deliveryStatus of the document
   */
  @JsonAdapter(DeliveryStatusEnum.Adapter.class)
  public enum DeliveryStatusEnum {
    CREATED("CREATED"),
    
    QUEUED("QUEUED"),
    
    ON_HOLD("ON_HOLD"),
    
    PROCESSING("PROCESSING"),
    
    DELIVERED("DELIVERED"),
    
    ERROR("ERROR");

    private String value;

    DeliveryStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DeliveryStatusEnum fromValue(String text) {
      for (DeliveryStatusEnum b : DeliveryStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DeliveryStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DeliveryStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DeliveryStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DeliveryStatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("deliveryStatus")
  private DeliveryStatusEnum deliveryStatus = null;

  @SerializedName("statusMessage")
  private String statusMessage = null;

   /**
   * The request date/time for this document in ISO 8601 format
   * @return requestTime
  **/
  @ApiModelProperty(value = "The request date/time for this document in ISO 8601 format")
  public OffsetDateTime getRequestTime() {
    return requestTime;
  }

   /**
   * The delivery date/time of this job in ISO 8601 format
   * @return deliveryTime
  **/
  @ApiModelProperty(value = "The delivery date/time of this job in ISO 8601 format")
  public OffsetDateTime getDeliveryTime() {
    return deliveryTime;
  }

  public IngestionResponse documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * Get documentId
   * @return documentId
  **/
  @ApiModelProperty(value = "")
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

   /**
   * The deliveryStatus of the document
   * @return deliveryStatus
  **/
  @ApiModelProperty(required = true, value = "The deliveryStatus of the document")
  public DeliveryStatusEnum getDeliveryStatus() {
    return deliveryStatus;
  }

   /**
   * A delivery status message, which can be informational, warning or error. A message here does not indicate an error per se
   * @return statusMessage
  **/
  @ApiModelProperty(value = "A delivery status message, which can be informational, warning or error. A message here does not indicate an error per se")
  public String getStatusMessage() {
    return statusMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IngestionResponse ingestionResponse = (IngestionResponse) o;
    return Objects.equals(this.requestTime, ingestionResponse.requestTime) &&
        Objects.equals(this.deliveryTime, ingestionResponse.deliveryTime) &&
        Objects.equals(this.documentId, ingestionResponse.documentId) &&
        Objects.equals(this.deliveryStatus, ingestionResponse.deliveryStatus) &&
        Objects.equals(this.statusMessage, ingestionResponse.statusMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestTime, deliveryTime, documentId, deliveryStatus, statusMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IngestionResponse {\n");
    
    sb.append("    requestTime: ").append(toIndentedString(requestTime)).append("\n");
    sb.append("    deliveryTime: ").append(toIndentedString(deliveryTime)).append("\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    deliveryStatus: ").append(toIndentedString(deliveryStatus)).append("\n");
    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

