/* 
 * Enterprise Integration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.EIP.Api;
using Sphereon.SDK.EIP.Model;
using Sphereon.SDK.EIP.Client;
using System.Reflection;

namespace Sphereon.SDK.EIP.Test
{
    /// <summary>
    ///  Class for testing DocumentDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentDetailsTests
    {
        // TODO uncomment below to declare an instance variable for DocumentDetails
        //private DocumentDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentDetails
            //instance = new DocumentDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentDetails
        /// </summary>
        [Test]
        public void DocumentDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentDetails
            //Assert.IsInstanceOfType<DocumentDetails> (instance, "variable 'instance' is a DocumentDetails");
        }

        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Test]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }
        /// <summary>
        /// Test the property 'StreamLocation'
        /// </summary>
        [Test]
        public void StreamLocationTest()
        {
            // TODO unit test for the property 'StreamLocation'
        }
        /// <summary>
        /// Test the property 'FileSize'
        /// </summary>
        [Test]
        public void FileSizeTest()
        {
            // TODO unit test for the property 'FileSize'
        }
        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }

    }

}
