/* 
 * Enterprise Integration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.EIP.Api;
using Sphereon.SDK.EIP.Model;
using Sphereon.SDK.EIP.Client;
using System.Reflection;

namespace Sphereon.SDK.EIP.Test
{
    /// <summary>
    ///  Class for testing DocumentPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentPayloadTests
    {
        // TODO uncomment below to declare an instance variable for DocumentPayload
        //private DocumentPayload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentPayload
            //instance = new DocumentPayload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentPayload
        /// </summary>
        [Test]
        public void DocumentPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentPayload
            //Assert.IsInstanceOfType<DocumentPayload> (instance, "variable 'instance' is a DocumentPayload");
        }

        /// <summary>
        /// Test the property 'DocumentDetails'
        /// </summary>
        [Test]
        public void DocumentDetailsTest()
        {
            // TODO unit test for the property 'DocumentDetails'
        }
        /// <summary>
        /// Test the property 'MetaDataPayloadType'
        /// </summary>
        [Test]
        public void MetaDataPayloadTypeTest()
        {
            // TODO unit test for the property 'MetaDataPayloadType'
        }
        /// <summary>
        /// Test the property 'MetaDataPayload'
        /// </summary>
        [Test]
        public void MetaDataPayloadTest()
        {
            // TODO unit test for the property 'MetaDataPayload'
        }

    }

}
