/* 
 * Enterprise Integration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.EIP.Api;
using Sphereon.SDK.EIP.Model;
using Sphereon.SDK.EIP.Client;
using System.Reflection;

namespace Sphereon.SDK.EIP.Test
{
    /// <summary>
    ///  Class for testing IngestionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IngestionResponseTests
    {
        // TODO uncomment below to declare an instance variable for IngestionResponse
        //private IngestionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IngestionResponse
            //instance = new IngestionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IngestionResponse
        /// </summary>
        [Test]
        public void IngestionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IngestionResponse
            //Assert.IsInstanceOfType<IngestionResponse> (instance, "variable 'instance' is a IngestionResponse");
        }

        /// <summary>
        /// Test the property 'RequestTime'
        /// </summary>
        [Test]
        public void RequestTimeTest()
        {
            // TODO unit test for the property 'RequestTime'
        }
        /// <summary>
        /// Test the property 'DeliveryTime'
        /// </summary>
        [Test]
        public void DeliveryTimeTest()
        {
            // TODO unit test for the property 'DeliveryTime'
        }
        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [Test]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'DeliveryStatus'
        /// </summary>
        [Test]
        public void DeliveryStatusTest()
        {
            // TODO unit test for the property 'DeliveryStatus'
        }
        /// <summary>
        /// Test the property 'StatusMessage'
        /// </summary>
        [Test]
        public void StatusMessageTest()
        {
            // TODO unit test for the property 'StatusMessage'
        }

    }

}
